name: Test

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build container
        run: |
          docker build -t bucket .

  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
      - name: Run unit tests
        run: |
          go test -v ./...

  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: unit
    env:
      ACCESS_KEY: test-access-key
      SECRET_KEY: test-secret-key
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build containers
        run: |
          docker compose build
      - name: Run integration tests
        run: |
          docker compose up tests
